packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': true
  core-js-pure: true
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@expo/cli@57.0.12'
  - '@expo/router-server@57.0.5'
  - expo-constants@57.0.9
  - expo-modules-core@57.0.9
  - expo@57.0.10
  - '@expo/ui@57.0.9'
  - expo-linking@57.0.5
  - expo-router@57.0.10
  - expo-auth-session@57.0.6

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js-pure
  - esbuild
  - sharp

overrides:
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
